config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'

  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  after_initialize :init

  enum priority: {
    low: 'low',
    medium: 'medium',
    high: 'high',
  }
    
  belongs_to :user  

  paginates_per 10
  max_paginates_per 100

  validates :title, presence: true
  validates :content, presence: true
  validates :date_taken, presence: true
  validates :user_id, presence: true
  validates :priority, presence: true
  validates :priority, inclusion: { in: priorities.keys }

  def init
    self.date_taken ||= Time.now
  end
  
  def self.searchable_columns
    [:title, :content]
  end

  def self.notes_for_user(user)
    Note.where(user: user)
  end

  def user_email
    self.user.email
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < AuthController
  before_action :set_note, only: [:edit, :update, :show, :destroy]
  before_action :check_owner, only: [:edit, :update, :show, :destroy]

  def index
    @search = params[:search]
    
    query_params = params.merge(user: current_user)

    @notes = NotesQuery.new(Note, query_params).perform_search
  end

  def new
    @note = Note.new
  end

  def edit; end

  def create
    @note = Note.new(note_params)

    if @note.save
      flash[:notice] = 'Note was successfully created'
      redirect_to note_path(@note)
    else
      render 'new'
    end
  end

  def update
    if @note.update(note_params)
      flash[:notice] = 'Note was successfully updated'
      redirect_to notes_path
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @note.destroy
    flash[:notice] = 'Note was successfully deleted'
    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    parse_date_taken

    params.require(:note).permit(:title, :content, :date_taken, :priority, :search).merge(user: current_user)
  end

  def parse_date_taken
    unless params['note']['date_taken'].blank?
      params['note']['date_taken'] = Time.strptime(params['note']['date_taken'], '%m/%d/%Y %I:%M %p').to_s
    end
  end

  def check_owner
    unless @note.user_id == current_user.id
      flash[:error] = 'Oops! You are not the owner of this note'
      redirect_to notes_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(type)
    case type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      type.to_s
    end
  end

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

  def destroy_link_to(path, options)
    link_to t('.destroy'), path,
      :method => :delete,
      :class => 'btn',
      :confirm => t('.destroy_confirm.body', :item => options[:item]),
      'data-confirm-fade' => true,
      'data-confirm-title' => t('.destroy_confirm.title', :item => options[:item]),
      'data-confirm-cancel' => t('.destroy_confirm.cancel', :item => options[:item]),
      'data-confirm-cancel-class' => 'btn-default',
      'data-confirm-proceed' => t('.destroy_confirm.proceed', :item => options[:item]),
      'data-confirm-proceed-class' => 'btn-danger'
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def note_date(date)
    date.strftime('Posted on %b, %d %Y - %H:%M')
  end

  def badge_class_for_priority(priority)
    case priority
    when 'low'
      'primary'
    when 'medium'
      'warning'
    when 'high'
      'danger'
    else
      'secondary'
    end
  end

  def priorities
    Note.priorities.keys.map { |priority| [priority.humanize, priority]}
  end
end

app/views/dashboard/index.html.erb
<h2>Welcome to Notes App</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Notes App</title>
    <%= csrf_meta_tags %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'shared/nav' if user_signed_in? %>
    <main class="container">
      <%= render 'shared/notification' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<div class="row bg-white border mb-3">
  <div class="col py-2">
    <%= form_for @note do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, placeholder: 'Place the note title', autofocus: true, required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %><br />
        <%= f.text_area :content, size: '20x5', placeholder: 'Place the note content', required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :priority %><br />
        <%= f.select :priority, priorities, { include_blank: 'Select priority...' }, { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.label :date_taken %><br />
        <%= react_component 'DateTimePicker',
              {
                value: @note.date_taken,
                name: "#{f.object_name}[date_taken]",
              } %>
      </div>

      <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/notes/_note.html.erb
<div class="row bg-white border mb-3">
  <div class="col">
    <div class="row my-2">
      <div class="col">
        <strong>You - <%= note.user_email %></strong>
      </div>
    </div>
    <div class="row my-2">
      <div class="d-flex col justify-content-between align-content-center">
        <strong><%= note.title %></strong>
        <span class="badge badge-<%= badge_class_for_priority(note.priority) %>">
          <%= note.priority %>
        </span>
      </div>
    </div>
    <div class="row my-2">
      <div class="col">
        <%= note_date(note.date_taken) %>
      </div>
    </div>
    <div class="row my-2">
      <div class="col">
        <p class="text-break"><%= note.content %></p>
      </div>
    </div>
    <div class="row my-3">
      <div class="col text-right">
        <%= link_to note_path(note), class: 'btn btn-primary' do %>
          Show
        <% end %>
        <%= link_to edit_note_path(note), class: 'btn btn-outline-primary' do %>
          Edit
        <% end %>
        <%= link_to note_path(note), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
          Delete
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/_search.html.erb
<div class="row justify-content-center bg-white border rounded py-3 mb-2">
    <%= form_tag notes_path, method: :get, class: 'input-group col-md' do %>
      <%= text_field_tag :search, @search, placeholder: 'Search...', class: 'form-control my-0 py-1' %>
      <span class='input-group-append'>
        <%= submit_tag 'Search', class: 'btn btn-outline-secondary' %>
      </span>
    <% end %>
</div>

app/views/notes/edit.html.erb
<div class="row justify-content-center bg-white border py-3 mb-2">
  <div class="col-sm-8">
    <h4>Edit Note - #<%= @note.id %></h4>
  </div>
  <div class="col-sm-4 text-right">
    <%= link_to notes_path, class: 'btn btn-primary' do %>
      <%= fa_icon 'arrow-left', class: 'mr-2' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/notes/index.html.erb
<div class="row justify-content-center bg-white border rounded py-3 mb-2">
  <div class="col-sm-8">
    <h4>Listing all notes</h4>
  </div>
  <div class="col-sm-4 text-right">
    <%= link_to new_note_path, class: 'btn btn-primary' do %>
      <%= fa_icon 'file', class: 'mr-2' %>
      New Note
    <% end %>
  </div>
</div>

<%= render 'search' %>

<%= render @notes %>

<div class="row justify-content-center">
  <%= paginate @notes, theme: 'twitter-bootstrap-4',
                      pagination_class: 'pagination-md',
                      nav_class: 'd-inline-b' %>
</div>

app/views/notes/new.html.erb
<div class="row justify-content-center bg-white border py-3 mb-2">
  <div class="col-sm-8">
    <h4>Create Note</h4>
  </div>
  <div class="col-sm-4 text-right">
    <%= link_to notes_path, class: 'btn btn-primary' do %>
      <%= fa_icon 'arrow-left', class: 'mr-2' %>
      Back
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/notes/show.html.erb
<div class="row justify-content-center bg-white border py-3 mb-2">
  <div class="col-sm-8">
    <h4>Note - #<%= @note.id %></h4>
  </div>
  <div class="col-sm-4 text-right">
    <%= link_to notes_path, class: 'btn btn-primary' do %>
      <%= fa_icon 'arrow-left', class: 'mr-2' %>
      Back
    <% end %>
  </div>
</div>

<div class="row bg-white border rounded mb-3">
  <div class="col py-2">
    <div class="row">
      <div class="d-flex col justify-content-between align-content-center">
        <strong> <%= @note.title %> </strong>
        <span class="badge badge-<%= badge_class_for_priority(@note.priority) %>">
          <%= @note.priority %>
        </span>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p class="text-break"> <%= @note.content %> </p>
      </div>
    </div>
    <div class="row">
      <div class="col text-right text-secondary">
        <small><%= note_date(@note.date_taken) %></small>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= fa_icon 'sticky-note 2x' %>
  <% end %>
  <button aria-controls="responsive-navbar-nav" type="button" aria-label="Toggle navigation" class="navbar-toggler collapsed">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="responsive-navbar-nav">
    <div class="ml-auto justify-content-end navbar-nav">
      <div class="nav-item <%= active_class('/') %>">
        <%= link_to root_path, class: 'nav-link' do %>
          Home <span class="sr-only">(current)</span>
        <% end %>
      </div>
      <div class="nav-item <%= active_class('/notes') %>">
        <%= link_to notes_path, class: 'nav-link' do %>
          Notes
        <% end %>
      </div>
      <div class="nav-item <%= active_class('/notes/new') %>">
        <%= link_to new_note_path, class: 'nav-link' do %>
          Create Note
        <% end %>
      </div>
      <div class="nav-item">
        <%= button_to destroy_user_session_path, class: 'btn btn-outline-primary', method: :delete do %>
          Logout
        <% end %>
      </div>
    </ul>
  </div>
</nav>

app/views/shared/_notification.html.erb
<div class="row">
  <div class="col">
    <% flash.each do |key, value| %>
      <div class="alert <%= bootstrap_class_for_flash(key) %> alert-dismissable fade show">
        <%= value %>
        <button class="close" data-dismiss="alert">&times;</button>
      </div>
    <% end %>
  </div>
</div>